[build]
publish = "build/web"
command = "flutter build web --release --web-renderer html --base-href='./'"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
force = true

[[headers]]
for = "/*"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"
  Access-Control-Allow-Origin = "*"
  Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
  Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept" 